# See: https://www.mkdocs.org/user-guide/configuration/

# Site configuration:
site_name: Aurora Documentation
site_author: NEAR Protocol
site_url: https://doc.aurora.dev
repo_url: https://github.com/aurora-is-near/doc.aurora.dev
google_analytics:

# Content configuration:
remote_name: origin
docs_dir: content
site_dir: public
use_directory_urls: false

# Theme configuration:
theme: material

# Plugin configuration:
plugins:
  - search
  - macros
  - mermaid2:
      arguments:
        theme: neutral

# Table of contents (TOC):
nav:
  - Introduction: index.md

# Mermaid plugin configuration:
extra_javascript:
  - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
