# See: https://www.mkdocs.org/user-guide/configuration/
---
# Site configuration:
site_name: Aurora Documentation
site_author: NEAR Protocol
site_url: https://doc.aurora.dev
repo_name: aurora-is-near/doc.aurora.dev
repo_url: https://github.com/aurora-is-near/doc.aurora.dev
google_analytics:

# Content configuration:
remote_name: origin
docs_dir: content
site_dir: public
use_directory_urls: false

# Table of contents (TOC):
nav:
  - Introduction: index.md

# Theme configuration:
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  custom_dir: theme

# Markdown configuration:
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

# Plugin configuration:
plugins:
  - search
  - macros
  - mermaid2:
      arguments:
        theme: neutral

# Custom CSS configuration:
extra_css:
  - _css/extra.css

# Custom JS configuration:
extra_javascript:
  - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
  - _js/extra.js

# Footer configuration:
extra:
  generator: false
  social:
    - name: Aurora on GitHub
      icon: fontawesome/brands/github
      link: https://github.com/aurora-is-near
    - name: Aurora on Discord
      icon: fontawesome/brands/discord
      link: https://discord.gg/jNjHYUF8vw
    - name: Aurora on Stack Overflow
      icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/questions/tagged/aurora+near
    - name: Aurora on Twitter
      icon: fontawesome/brands/twitter
      link: https://twitter.com/auroraisnear
